# MSM8660 WILL CONTAIN ANY MISSING (GPS, RIL, WIFI)
# INFORMATION.
-include device/htc/msm8660-common/BoardConfigCommon.mk

# BOOTLOADER
TARGET_BOOTLOADER_BOARD_NAME := pyramid

# KERNEL
BOARD_KERNEL_BASE := 0x48000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_CMDLINE := console=ttyHSL0 android.boot.hardware=pyramid no_console_suspend=1
TARGET_KERNEL_SOURCE := kernel
TARGET_KERNEL_CONFIG := pyramid_defconfig

# BOOT
TARGET_SCREEN_HEIGHT := 960
TARGET_SCREEN_WIDTH := 540

# PARTITIONS
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16776192
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 838859776
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1252770816
BOARD_FLASH_BLOCK_SIZE := 262144
